import mongoose from "mongoose";

const Schema = mongoose.Schema;

export const accountDetails = mongoose.model("AccountDetails",new Schema({
    userId: String,
    accountId: String,
    name: String,
    printAs: String,
    group: String,
    openingBal: Number,
    DR_CR: String,
    taxNo: String,
    Address1: String,
    Address2: String,
    city: String,
    pincode: Number,
    state: String,
    stateCode: String,
    mobileNo: String,
    phone: String,
    email: String,
    contactPerson: String,
    panCardNo: String,
    },
    { timestamps: true }
), "AccountDetails");

export const groupAccount = mongoose.model("GroupAccountDetails", new Schema ({
    groupAccountId: String,
    primaryGroup: String,
    group: String,
    underGroup: String
}), "GroupAccountDetails");

export const Account = mongoose.model("newAccount", new Schema ({
    userId: String,
    AccountId: String,
    AccountName: String,
    GroupName: String,
    OpBal: Number,
    Dr_Cr: String,
    AddressLine1: String,
    AddressLine2: String,
    City: String,
    State: String,
    Phone: Number,
    Mobile: Number,
    Email: String,
    ContactPerson: String,
    Birthday: String,
    Anniversary: String,
    BankName: String,
    BankAccountNo: Number,
    ChequePricingName: String,
    PartyType: String,
    VAT_NO: Number,
    CST_NO: Number,
    ITPAN: Number,
    DL_No1: Number,
    DL_NO2: String,
    BillByBill: String,
    CreditLimit: Number,
    BillLimit: Number,
    CreditDaysSale: Number,
    CreditDaysPurchase: Number,
    AdditionalField1: String,
    AdditionalField2: String,
    AdditionalField3: String,
    AdditionalField4: String,
    AdditionalField5: String,
    AdditionalField6: String,
    AdditionalField7: String,
    AdditionalField8: String,
    AdditionalField9: String,
    AdditionalField10: String,
    PrintName: String,
    GSTNo: Number,
    UCardNo: Number,
    MyOpBal: Number,
    My_D_C: String,
    AadharNo: Number,
    StateCode: Number,
    Pincode: Number,
    AccountID: Number
}));